#!/usr/bin/env bash
# Retrieves IBM Cloud credentials and writes them to .env
set -euo pipefail

ENV_FILE="$(dirname "$0")/.env"

echo "==> Logging in to IBM Cloud..."
ibmcloud login --sso -q

echo ""
echo "==> Fetching IBM Cloud API key..."
API_KEY_JSON=$(ibmcloud iam api-key-create translator-agent-key -d "watsonx Translator Agent" --output json)
IBM_CLOUD_API_KEY=$(echo "$API_KEY_JSON" | jq -r '.apikey')
echo "    Created API key: $(echo "$API_KEY_JSON" | jq -r '.name')"

echo ""
echo "==> Fetching IAM token for watsonx project lookup..."
IAM_TOKEN=$(ibmcloud iam oauth-tokens --output json | jq -r '.iam_token')

echo ""
echo "==> Fetching watsonx projects..."
PROJECTS=$(curl -sf -X GET "https://api.dataplatform.cloud.ibm.com/v2/projects" \
  -H "Authorization: $IAM_TOKEN")

PROJECT_COUNT=$(echo "$PROJECTS" | jq '.total_results')
if [[ "$PROJECT_COUNT" -eq 0 ]]; then
  echo "    No watsonx projects found. Create one at cloud.ibm.com first."
  exit 1
elif [[ "$PROJECT_COUNT" -eq 1 ]]; then
  WATSONX_PROJECT_ID=$(echo "$PROJECTS" | jq -r '.resources[0].metadata.guid')
  echo "    Using project: $(echo "$PROJECTS" | jq -r '.resources[0].entity.name') ($WATSONX_PROJECT_ID)"
else
  echo ""
  echo "    Multiple projects found — pick one:"
  echo "$PROJECTS" | jq -r '.resources[] | "    \(.metadata.guid)  \(.entity.name)"'
  echo ""
  read -rp "    Enter project ID: " WATSONX_PROJECT_ID
fi

echo ""
echo "==> Fetching COS HMAC credentials..."
HMAC_JSON=$(ibmcloud resource service-key translator-hmac --output json 2>/dev/null || true)

if [[ -z "$HMAC_JSON" || "$HMAC_JSON" == "[]" ]]; then
  echo "    HMAC key 'translator-hmac' not found — creating it..."
  ibmcloud resource service-key-create translator-hmac Writer \
    --instance-name CloudObjectStorage \
    --parameters '{"HMAC": true}' -q
  HMAC_JSON=$(ibmcloud resource service-key translator-hmac --output json)
fi

OUTPUT_COS_ACCESS_KEY=$(echo "$HMAC_JSON" | jq -r '.[0].credentials.cos_hmac_keys.access_key_id')
OUTPUT_COS_SECRET_KEY=$(echo "$HMAC_JSON" | jq -r '.[0].credentials.cos_hmac_keys.secret_access_key')
echo "    Retrieved HMAC credentials."

echo ""
read -rp "==> Enter your COS bucket name: " OUTPUT_COS_BUCKET

echo ""
echo "==> Fetching Code Engine app URL..."
APP_URL=$(ibmcloud ce app get --name watsonx-translator --output json 2>/dev/null | jq -r '.status.url // empty')
if [[ -z "$APP_URL" ]]; then
  APP_URL="http://localhost:8000"
  echo "    App not deployed yet — defaulting to $APP_URL"
else
  echo "    $APP_URL"
fi

echo ""
echo "==> Writing $ENV_FILE ..."
cat > "$ENV_FILE" <<EOF
# ── watsonx AI Translator Agent Configuration ───────────────────────
# Generated by setup-env.sh — do not commit this file.

# Required
IBM_CLOUD_API_KEY=$IBM_CLOUD_API_KEY
WATSONX_PROJECT_ID=$WATSONX_PROJECT_ID

# Optional: Override defaults
APP_URL=$APP_URL
WATSONX_URL=https://us-south.ml.cloud.ibm.com
WATSONX_API_VERSION=2024-05-01
CHUNK_SIZE=3000

# Optional: IBM COS output bucket
OUTPUT_COS_ENDPOINT=https://s3.us-south.cloud-object-storage.appdomain.cloud
OUTPUT_COS_BUCKET=$OUTPUT_COS_BUCKET
OUTPUT_COS_ACCESS_KEY=$OUTPUT_COS_ACCESS_KEY
OUTPUT_COS_SECRET_KEY=$OUTPUT_COS_SECRET_KEY
EOF

echo ""
echo "Done. Edit OUTPUT_COS_BUCKET in .env if needed, then run:"
echo "  uvicorn main:app --host 0.0.0.0 --port 8000"
